### ISSUE TITLE
Installer fails on CentOS 6.6

### ISSUE THREAD

**Issue by damacus** [universityofderby/chef-oracle-client#3]
Installer fails without rsync and unzip installed.

**Comment by damacus** [comment]
Shouldn't fail because yeah: 
https://github.com/universityofderby/chef-oracle-client/blob/master/libraries/oracle_client.rb#L70

**Comment by damacus** [comment]
Raised as a bug on the resource cookbook: 
https://github.com/chef-cookbooks/resource/issues/28

**Comment by damacus** [comment]
You can work around this problem for now by installing the required packages in the wrapper cookbook where you're calling the oracle-client resource from.

**Comment by hanskreuger** [comment]
Why do you think this is a resource cookbook bug?
