### ISSUE TITLE
Response file missing parameter for 11.2.0.4

### ISSUE THREAD

**Issue by jujugrrr** [universityofderby/chef-oracle-client#9]
Getting the following error: 
```
 Please wait ...[FATAL] [INS-10105] The given response file /tmp/kitchen/cache/oracle-client-11.2.0.4/client-11.rsp is not valid.
```
In https://github.com/universityofderby/chef-oracle-client/blob/master/templates/default/client-11.rsp.erb, we are missing : 
```
oracle.installer.autoupdates.option=SKIP_UPDATES
```

The cookbook doesn't allow to use another template.

**Comment by jujugrrr** [comment]
Happy to help and contribute if this cookbook is still active 😉

**Comment by richardlock** [comment]
Hi Julien,

Thanks.  I'm just adding in some properties to allow the templates to be overriden.  Testing the changes at the moment.

Richard

**Comment by richardlock** [comment]
Hi Julien,

Does that work for you now with allowing the templates to be overriden?  Happy if you want to contribute additional code for the response file, etc.

Thanks, Richard

**Comment by jujugrrr** [comment]
Hi @richardlock 

> Does that work for you now with allowing the templates to be overriden? Happy if you want to contribute additional code for the response file, etc.

I've done it in a fork too, but then I had other issue with some of the installer options not working for us. And some of the return code(6) from the installer looked fine for us but not supported by the cookbook(https://docs.oracle.com/cd/E11857_01/em.111/e12255/oui4_product_install.htm#i1005899). I don't have much experience with Oracle products and different versions. So I ended up creating a small recipe which matches what we were scripting before, as I don't have much time to work on this cookbook.

Sorry about that!

**Comment by richardlock** [comment]
Ok, thanks for looking.  We don't really use this cookbook much now as we developed a new one for use with PeopleSoft.  This is based on the pre-packaged oracle-client in the PeopleTools DPKs and includes resources for oracle-client as well as quite a few other components.

https://github.com/universityofderby/chef-peopletools/blob/master/resources/deployment/oracle_client.rb

Kind regards, Richard
